version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: notes
      POSTGRES_USER: notesadmin
      POSTGRES_PASSWORD: notespassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
volumes:
  postgres_data:
